spring:
  application:
    name: hab-provider
    version: 1.0
  activemq:
    broker-url: tcp://localhost:61616 # activemq broker Url config
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
    queue-name: test.msg.queue
    out-queue-name: test.msg.out-queue
    topic-name: test.msg.topic
server:
  port: 9090